spring.application.name=demo-devops-aymen-wajdi
server.port=8090

spring.datasource.url=jdbc:mysql://mysql-service:3306/projectfed?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus

# Nom de l?application pour Prometheus
management.metrics.tags.application=demo-devops-aymen-wajdi