apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: myapp.local
      http:
        paths:
          # Angular frontend
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: angular-frontend-service
                port:
                  number: 80
          # Spring Boot API
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: springboot-service
                port:
                  number: 8090
