name: CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  # ======================================================
  # 1. TESTS + ANALYSE CODE
  # ======================================================
  test-and-analysis:
    name: Tests & Code Analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build & Run Tests with Coverage
        run: |
          mvn clean verify
          mvn jacoco:report

      - name: Verify JaCoCo Report
        run: test -f target/site/jacoco/jacoco.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=wajdibenameur_dev-test-ops-aymen-wajdi
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.junit.reportPaths=target/surefire-reports
            -Dsonar.branch.name=${{ github.ref_name }}

  # ======================================================
  # 2. DOCKER BUILD + TRIVY + PUSH
  # ======================================================
  docker-deploy:
    name: Build, Scan & Push Docker Image
    runs-on: ubuntu-latest
    needs: test-and-analysis

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build JAR
        run: mvn clean package -DskipTests

      - uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Generate image tags
        run: |
          BRANCH=${GITHUB_REF_NAME}
          DATE=$(date +%Y%m%d%H%M%S)
          SHA=${GITHUB_SHA::8}
          echo "IMAGE_NAME=wajdiuser/projectfed" >> $GITHUB_ENV
          echo "IMAGE_TAG=${BRANCH}-${DATE}-${SHA}" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:latest \
            -t $IMAGE_NAME:$IMAGE_TAG .

      - name: Security Scan with Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Push Docker images
        run: |
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:$IMAGE_TAG
# ======================================================
# 2b. BUILD + DOCKER FRONTEND
# ======================================================
  frontend-deploy:
    name: Build & Deploy Angular Frontend
    runs-on: ubuntu-latest
    needs: docker-deploy  # attendre que backend soit build et pushé

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # version LTS
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install Angular CLI
        run: npm install -g @angular/cli
        working-directory: ./frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend  # mettre le chemin de ton projet Angular

      - name: Build Angular Production
        run: ng build --configuration production
        working-directory: ./frontend

      - name: Build Docker image for frontend
        run: |
          FRONT_IMAGE_NAME=wajdiuser/frontend-projectfed
          DATE=$(date +%Y%m%d%H%M%S)
          SHA=${GITHUB_SHA::8}
          FRONT_IMAGE_TAG=prod-$DATE-$SHA
          echo "FRONT_IMAGE_NAME=$FRONT_IMAGE_NAME" >> $GITHUB_ENV
          echo "FRONT_IMAGE_TAG=$FRONT_IMAGE_TAG" >> $GITHUB_ENV
          docker build -t $FRONT_IMAGE_NAME:latest -t $FRONT_IMAGE_NAME:$FRONT_IMAGE_TAG ./frontend
          docker push $FRONT_IMAGE_NAME:latest
          docker push $FRONT_IMAGE_NAME:$FRONT_IMAGE_TAG

      - name: Deploy Frontend on Minikube
        if: success()
        shell: bash
        run: |
          kubectl apply -f k8s/frontend-deployment.yaml
          kubectl apply -f k8s/frontend-service.yaml
          kubectl get pods -o wide

  # ======================================================
# 3. DEPLOIEMENT KUBERNETES (MINIKUBE)
# ======================================================
  kubernetes-deploy:
    name: Deploy to Minikube Kubernetes
    runs-on: [ self-hosted, Windows, X64 ]
    needs: docker-deploy

    steps:
      - uses: actions/checkout@v4

      - name: Check Minikube status
        shell: powershell
        run: |
          minikube status
          kubectl version --client
          kubectl config current-context

      - name: Start Minikube
        shell: powershell
        run: |
          minikube start --driver=docker

      - name: Create MySQL Secret from GitHub Secrets
        shell: powershell
        run: |
          kubectl create secret generic mysql-secret `
            --from-literal=MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }} `
            --from-literal=MYSQL_USER=${{ secrets.MYSQL_USER }} `
            --from-literal=MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }} `
            --from-literal=MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }} `
            --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy MySQL
        shell: powershell
        run: kubectl apply -f k8s/mysql.yml

      - name: Wait for MySQL to be ready
        shell: powershell
        run: |
          # Attendre que le pod MySQL soit ready avant de continuer
          kubectl wait --for=condition=ready pod -l app=mysql --timeout=120s

      - name: Deploy Spring Boot App
        shell: powershell
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml

      - name: Check Pods Status
        shell: powershell
        run: kubectl get pods -o wide
# ======================================================
# 4. DEPLOIEMENT MONITORING (Prometheus + Grafana)
# ======================================================
  monitoring-deploy:
    name: Deploy Prometheus & Grafana
    runs-on: [ self-hosted, Windows, X64 ]
    needs: kubernetes-deploy

    steps:
      - uses: actions/checkout@v4

      - name: Apply Prometheus
        shell: powershell
        run: |
          kubectl apply -f k8s/prometheus.yml

      - name: Apply Grafana
        shell: powershell
        run: |
          kubectl apply -f k8s/grafana.yml

      - name: Wait for Monitoring Pods Ready
        shell: powershell
        run: |
          kubectl wait --for=condition=ready pod -l app=prometheus -n monitoring --timeout=120s
          kubectl wait --for=condition=ready pod -l app=grafana -n monitoring --timeout=120s

      - name: Show Pods Status
        shell: powershell
        run: kubectl get pods -n monitoring -o wide
